<?php

/**
 * @file
 * Main functionality file for the spaces module.
 */

/**
 * Implements hook_init().
 */
function spaces_init() {
  global $conf;

  if (!$space_context = spaces_context()) {
    return;
  }

  if (!$spaces = spaces_load_entity_spaces($space_context[0], $space_context[1])) {
    return;
  }

  foreach ($spaces as $space) {
    $conf = drupal_array_merge_deep($conf, $space->settings['variables']);
  }
}

/**
 * Get the current context.
 */
function spaces_context() {
  $context = &drupal_static(__FUNCTION__, FALSE);

  if (!empty($context)) {
    return $context;
  }

  $context = spaces_determine_context();

  return $context;
}

/**
 * Determine the context of the current space.
 *
 * @param $item
 *  Optional; A menu item that context should be extracted from. If empty
 *  defaults to the current menu item by using menu_get_item().
 *
 * @return
 *  The current context of the user.
 */
function spaces_determine_context($item = NULL) {
  if (!$enabled = variable_get("spaces_context_spaces")) {
    return;
  }

  $item = $item ? $item : menu_get_item();

  // Get all the methods and order them by the weight.
  $weights = variable_get("spaces_providers_weight_spaces");

  $plugins = spaces_get_spaces_styles();

  foreach ($plugins as $id => &$plugin) {
    if (empty($enabled[$id])) {
      unset($plugins[$id]);
    }
    $plugin['weight'] = $weights[$id];
  }
  uasort($plugins, 'drupal_sort_weight');

  // Get the all the determine context plugins.
  $method = NULL;
  unset($plugin);
  foreach ($plugins as $plugin) {
    if (!empty($plugin['path'])) {
      foreach ($plugin['path'] as $path) {
        if (strpos($item['path'], $path) === 0) {
          $method = $plugin;
          break 2;
        }
      }
    }
  }

  // Get the first plugin provider.
  if (!empty($method)) {
    $value = call_user_func($method['determine_function'], $item);
  }
  else {
    $plugin = reset($plugins);
    $value = call_user_func($plugin['determine_function'], $item);
  }

  return reset($value);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function spaces_ctools_plugin_api($module, $api) {
  if ($module == 'spaces' && $api == 'spaces_context') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function spaces_ctools_plugin_type() {
  $plugins['spaces_context'] = array(
    'classes' => array('class'),
    'process' => 'spaces_plugin_process',
  );
  return $plugins;
}

/**
 * Add defaults values to the notifier plugins.
 *
 * - 'description': The description of the plugin.
 */
function spaces_plugin_process(&$plugin, $info) {
  $plugin += array(
    'description' => '',
    'options' => array(),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function spaces_ctools_plugin_directory($module, $plugin) {
  if ($module == 'spaces') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Helper function to include CTools plugins and get a notifier plugin.
 *
 * @param $plugin_name
 *   The plugin that should be loaded.
 *
 * @return array
 */
function spaces_get_spaces_style($style_name) {
  ctools_include('plugins');
  return ctools_get_plugins('spaces', 'spaces_context', $style_name);
}

/**
 * Helper function to include CTools plugins and get all notifier plugins.
 */
function spaces_get_spaces_styles() {
  ctools_include('plugins');
  return ctools_get_plugins('spaces', 'spaces_context');
}

/**
 * Implements hook_entity_info().
 */
function spaces_entity_info() {
  $return = array(
    'space' => array(
      'label' => t('Space'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'Space',
      'base table' => 'space',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
        'label' => 'title',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
    ),
  );

  return $return;
}

/**
 * Create a base object of the space app entity.
 *
 * @param $type
 *  The type of the space.
 * @param $values
 *  Overriding the entity settings.
 * @return Space
 */
function spaces_create($type, $entity_type, $entity_id, $values = array()) {
  $values['type'] = $type;
  $values['entity_type'] = $entity_type;
  $values['entity_id'] = $entity_id;

  return entity_create('space', $values);
}

/**
 * Loading a single spaces instance.
 *
 * @param $id
 *  The identifier of the space instance.
 * @return Space
 *  A space object.
 */
function spaces_load($id) {
  $spaces = spaces_load_multiple(array($id));
  return reset($spaces);
}

/**
 * Loading multiple spaces instances.
 *
 * @param $ids
 *  Array of spaces ID's.
 */
function spaces_load_multiple($ids) {
  return entity_load('space', $ids);
}

/**
 * Loading spaces referenced to an entity.
 *
 * @param $entity_type
 *  The entity type.
 * @param $data
 *  The entity object or identifier.
 *
 * @return
 *  All the referenced spaces.
 */
function spaces_load_entity_spaces($entity_type, $data) {
  $wrapper = entity_metadata_wrapper($entity_type, $data);

  // Load all the spaces for the node the user watching.
  $query = new entityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'space')
    ->propertyCondition('entity_id', $wrapper->getIdentifier())
    ->propertyCondition('entity_type', $wrapper->type())
    ->propertyCondition('type', $wrapper->getBundle())
    ->propertyCondition('status', 1)
    ->execute();

  if (empty($result['space'])) {
    return array();
  }

  return spaces_load_multiple(array_keys($result['space']));
}
