<?php

/**
 * @file
 * Main functionality file for the spaces module.
 */

/**
 * Define an enabled Space status.
 */
define('SPACES_SPACE_ENABLED', TRUE);

/**
 * Define a disabled Space status.
 */
define('SPACES_SPACE_DISABLED', FALSE);

/**
 * Implements hook_init().
 *
 * Allow spaces to override $conf.
 */
function spaces_init() {
  spaces_invoke_overrides('variables');
}

/**
 * Implements hook_context_load_alter().
 */
function spaces_context_load_alter(&$context) {
  spaces_invoke_overrides('context', $context);
}

/**
 * @param $plugin_name
 * @param array $spaces_context
 */
function spaces_invoke_overrides($plugin_name, &$data = NULL) {
  if (!$spaces_context = spaces_context()) {
    return;
  }

  $spaces = array();
  foreach ($spaces_context as $entity_type => $ids) {
    $spaces = array_merge($spaces, spaces_load_spaces_by_entity($entity_type, $ids));
  }

  if (!$spaces) {
    return;
  }

  foreach ($spaces as $space) {
    $space->getOverride($plugin_name)->override($data);
  }
}

/**
 * Get the current context.
 */
function spaces_context() {
  $spaces_context = &drupal_static(__FUNCTION__, FALSE);

  if (!empty($spaces_context)) {
    return $spaces_context;
  }

  $spaces_context = spaces_determine_context();

  return $spaces_context;
}

/**
 * Determine the context of the current page.
 *
 * @return
 *  The current context of the user.
 */
function spaces_determine_context() {
  $defaults = array('node' => -4, 'user' => -3);
  if (!$enabled = variable_get("spaces_context_spaces", $defaults)) {
    return;
  }

  // Get all the methods and order them by the weight.
  $weights = variable_get("spaces_providers_weight_spaces");

  $plugins = spaces_get_spaces_contexts();

  foreach ($plugins as $id => &$plugin) {
    if (empty($enabled[$id])) {
      unset($plugins[$id]);
    }
    $plugin['weight'] = $weights[$id];
  }
  uasort($plugins, 'drupal_sort_weight');

  $spaces_context = array();

  // Get the all the determine context plugins.
  foreach ($plugins as $plugin) {
    if (!$value = call_user_func($plugin['determine_function'])) {
      continue;
    }

    // @todo: Use plugin to get the function.
    $spaces_context = array_merge_recursive($spaces_context, $value);
  }

  return $spaces_context;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function spaces_ctools_plugin_api($module, $api) {
  if ($module == 'spaces' && $api == 'spaces_context') {
    return array('version' => 1);
  }
  elseif ($module == 'spaces' && $api == 'spaces_override') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function spaces_ctools_plugin_type() {
  $plugins['spaces_context'] = array(
    'classes' => array('class'),
    'process' => 'spaces_context_plugin_process',
  );

  $plugins['spaces_override'] = array(
    'classes' => array('class'),
    'process' => 'spaces_override_plugin_process',
  );
  return $plugins;
}

/**
 * Add defaults values to the notifier plugins.
 *
 * - 'description': The description of the plugin.
 */
function spaces_context_plugin_process(&$plugin, $info) {
  $plugin += array(
    'description' => '',
    'options' => array(),
  );
}

/**
 * Add defaults values to the notifier plugins.
 *
 * - 'description': The description of the plugin.
 */
function spaces_override_plugin_process(&$plugin, $info) {
  $plugin['options'] += array(
    'settings_key' => $plugin['name'],
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function spaces_ctools_plugin_directory($module, $plugin) {
  if ($module == 'spaces') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Helper function to include CTools plugins and get a notifier plugin.
 *
 * @param $plugin_name
 *   The plugin that should be loaded.
 *
 * @return array
 */
function spaces_get_spaces_context($plugin_name) {
  ctools_include('plugins');
  return ctools_get_plugins('spaces', 'spaces_context', $plugin_name);
}

/**
 * Helper function to include CTools plugins and get all notifier plugins.
 */
function spaces_get_spaces_contexts() {
  ctools_include('plugins');
  return ctools_get_plugins('spaces', 'spaces_context');
}

/**
 * Helper function to include CTools plugins and get a notifier plugin.
 *
 * @param $plugin_name
 *   The plugin that should be loaded.
 *
 * @return array
 */
function spaces_get_spaces_override($plugin_name) {
  ctools_include('plugins');
  return ctools_get_plugins('spaces', 'spaces_override', $plugin_name);
}

/**
 * Helper function to include CTools plugins and get all notifier plugins.
 */
function spaces_get_spaces_overrides() {
  ctools_include('plugins');
  return ctools_get_plugins('spaces', 'spaces_override');
}

/**
 * Implements hook_entity_info().
 */
function spaces_entity_info() {
  $return = array(
    'space' => array(
      'label' => t('Space'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'Space',
      'base table' => 'space',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
        'label' => 'title',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
    ),
  );

  return $return;
}

/**
 * Create a base object of the space app entity.
 *
 * @param $type
 *  The type of the space.
 * @param $values
 *  Overriding the entity settings.
 * @return Space
 */
function spaces_create($type, $entity_type, $entity_id, $values = array()) {
  $values['type'] = $type;
  $values['entity_type'] = $entity_type;
  $values['entity_id'] = $entity_id;

  $values += array(
    'status' => TRUE,
  );

  return entity_create('space', $values);
}

/**
 * Loading a single spaces instance.
 *
 * @param $id
 *  The identifier of the space instance.
 * @return Space
 *  A space object.
 */
function spaces_load($id) {
  $spaces = spaces_load_multiple(array($id));
  return reset($spaces);
}

/**
 * Loading multiple spaces instances.
 *
 * @param $ids
 *  Array of spaces ID's.
 */
function spaces_load_multiple($ids) {
  return entity_load('space', $ids);
}

/**
 * Loading spaces referenced to an entity.
 *
 * @param $entity_type
 *  The entity type.
 * @param $data
 *  The entity object or identifier.
 *
 * @return
 *  All the referenced spaces.
 */
function spaces_load_spaces_by_entity($entity_type, $ids = array(), $space_bundle = FALSE) {
  // Load all the spaces for the node the user watching.
  $query = new entityFieldQuery();
  $query
    ->entityCondition('entity_type', 'space')
    ->propertyCondition('entity_type', $entity_type)
    ->propertyCondition('entity_id', $ids, 'IN')
    ->propertyCondition('status', SPACES_SPACE_ENABLED)
    ->execute();

  if ($space_bundle) {
    $query->entityCondition('bundle', $space_bundle);
  }

  $result = $query->execute();

  return !empty($result['space']) ? spaces_load_multiple(array_keys($result['space'])) : array();
}
